### ISSUE TITLE
Compatibility with unicode-math

### ISSUE THREAD

**Issue by MaxNoe** [urdh/skmath#27]
The package seems to be incompatible with unicode math.

I tried compiling using lualatex with the given minimal document:

```latex
\documentclass{scrartcl}

\usepackage{fontspec}


\usepackage{unicode-math}
\setmathfont[
  math-style=ISO,
  bold-style=ISO,
  nabla=upright,
  partial=upright,
]{Latin Modern Math}

\usepackage{skmath}

\begin{document}

\begin{equation}
  \N, \Z, \Q, \R, \C
\end{equation}

\begin{equation}
  \norm{\symbf{v}}
\end{equation}

\begin{equation}
  \abs{\symbf{v}}
\end{equation}

\begin{equation}
  \int_0^1 \sin{x} \d{x}
\end{equation}

\end{document}
```

**Comment by urdh** [comment]
[The _unicode-math_ manual](http://mirrors.rit.edu/CTAN/macros/latex/contrib/unicode-math/unicode-math.pdf) notes on page three that it ”should be loaded after any other maths or font-related package in case it needs to overwrite their definitions”. Modifying your example so that _skmath_ is loaded before _unicode-math_ works for me and produces the desired output as far as I can tell.

**Comment by MaxNoe** [comment]
Ah, dam. I tried it the other way around before but I had an undefined control sequence error because I forgot the `commonsets` option
